name: Hello World
on: 
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A demo build"
