name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    if: github.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building the application"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying the application"
