name: If Demo
on:
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref == "refs/heads/main" 
        run: echo "Running for main branch"
      - name: Run this step
        run: echo "Running this step"
