name: If Demo
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main'
        run: echo "Running for main branch"
      - name: Run this step
        run: echo "Running this step"
