name: Nice If example
on:
    push:
        branches:
            - main
            - develop
            - feature/**
jobs:
    quality_cheks:
        if: startsWith(github.ref_name,'feature') && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Perform code quality
              run: |
                echo "Performing quality checks on the code"
                exit 1
    dev_deploy:
        if: github.ref_name == 'develop' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Dev Deploy
              run: echo "Deploying the code to development environment"
    prod_deploy:
        if: github.ref_name == 'main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Prod Deploy
              run: echo "Deploying the code to production environment"
    success_notify:
        needs: ['quality_cheks','dev_deploy','prod_deploy']
        if: always() && !failure()
        runs-on: ubuntu-latest
        steps:
            - name: Notify Success
              run: echo "Success email sent to the team"
    failure_notify:
        needs: ['quality_cheks','dev_deploy','prod_deploy']
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Notify Failure
              run: echo "Failure email sent to the team"