name: Or Condition Demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Hari or Javahometech
        if: github.actor == 'Hari' || github.actor == 'javahometech'
        run: echo "It is triggered by either Hari or Javahometech"
